framework:
    messenger:
        transports:
            # Use the enqueue transport
            async: 'enqueue://default'

        routing:
            # Route your messages to the transports
            'App\Message\SmsNotification': async
