framework:
    messenger:
        default_bus: bus1
        buses:
            bus1: ~
            bus2: ~

        transports:
            # Use the enqueue transport
            async: 'amqp://user:pass@localhost/messages'

        routing:
            # Route your messages to the transports
            'App\Message\SmsNotification': async
